import type { AssessmentData, Recommendation, BenchmarkData } from './types'

export const defaultAssessment: AssessmentData = {
  documentName: 'National AI Strategy 2025-2030',
  country: 'Tanzania',
  assessmentDate: 'May 19, 2026',
  overallScore: 42,
  readinessLevel: 'Developing',
  dimensions: [
    { name: 'AI Policy & Strategy', score: 55, level: 'Emerging', keyFinding: 'Formal AI strategy exists but lacks actionable implementation plans and dedicated funding mechanisms.' },
    { name: 'Strategy Alignment', score: 48, level: 'Developing', keyFinding: 'Partial alignment with SDGs and AU Digital Transformation Strategy; weak linkage to national development plan.' },
    { name: 'Data & Model Ecosystem', score: 32, level: 'Developing', keyFinding: 'Data protection law exists but no open data policy or AI model marketplace framework.' },
    { name: 'Cross-Domain Correlation', score: 38, level: 'Developing', keyFinding: 'AI mentioned across health and agriculture sectors but lacks depth in education and finance.' },
    { name: 'Human Impact & Inclusion', score: 28, level: 'Nascent', keyFinding: 'No digital literacy strategy, gender inclusion targets, or AI-driven job displacement mitigation.' },
    { name: 'Digital Infrastructure', score: 45, level: 'Developing', keyFinding: 'Broadband coverage at 42%; cloud infrastructure nascent; no national compute resource strategy.' },
    { name: 'Contextualization & Regional Fit', score: 50, level: 'Emerging', keyFinding: 'Some localization of AI use cases to agriculture and health but limited multi-lingual support.' },
  ],
  gaps: [
    { id: "1", description: 'No dedicated AI funding mechanism or budget allocation in national strategy', dimension: 'AI Policy & Strategy', indicator: 'ITU-AI-RF 2.0 — Indicator 1.3', severity: 'Critical', recommendation: 'Establish a National AI Innovation Fund with annual budget allocation from Ministry of Finance.' },
    { id: "2", description: 'Data governance framework lacks AI-specific provisions for training data and model accountability', dimension: 'Data & Model Ecosystem', indicator: 'ITU-AI-RF 2.0 — Indicator 3.2', severity: 'Critical', recommendation: 'Enact AI-specific data governance regulations covering training data provenance and model accountability.' },
    { id: "3", description: 'No AI ethics framework, impact assessment requirement, or human oversight mechanism', dimension: 'AI Policy & Strategy', indicator: 'ITU-AI-RF 2.0 — Indicator 1.5', severity: 'Critical', recommendation: 'Develop a National AI Ethics Framework aligned with UNESCO AI Ethics Recommendations.' },
    { id: "4", description: 'No comprehensive digital literacy program targeting rural populations', dimension: 'Human Impact & Inclusion', indicator: 'ITU-AI-RF 2.0 — Indicator 5.1', severity: 'Critical', recommendation: 'Launch a National Digital Literacy Initiative targeting 60% coverage in rural areas within 3 years.' },
    { id: "5", description: 'AI skilling and workforce transition plan absent — no mention of job displacement', dimension: 'Human Impact & Inclusion', indicator: 'ITU-AI-RF 2.0 — Indicator 5.3', severity: 'Critical', recommendation: 'Develop an AI Workforce Transition Plan with reskilling programs and social safety nets.' },
    { id: "6", description: 'No gender-inclusive AI targets or gender-disaggregated data collection mandate', dimension: 'Human Impact & Inclusion', indicator: 'ITU-AI-RF 2.0 — Indicator 5.2', severity: 'Moderate', recommendation: 'Mandate gender-disaggregated data collection and set minimum 40% female participation targets in AI programs.' },
    { id: "7", description: 'National broadband plan not integrated with AI infrastructure roadmap', dimension: 'Digital Infrastructure', indicator: 'ITU-AI-RF 2.0 — Indicator 6.1', severity: 'Moderate', recommendation: 'Integrate broadband expansion with AI infrastructure requirements in the national connectivity plan.' },
    { id: "8", description: 'No national compute resource strategy for AI workloads', dimension: 'Digital Infrastructure', indicator: 'ITU-AI-RF 2.0 — Indicator 6.4', severity: 'Moderate', recommendation: 'Develop a National Compute Strategy including public cloud procurement, GPU infrastructure, and research compute grants.' },
    { id: "9", description: 'AI strategy weakly linked to national development plan and SDG targets', dimension: 'Strategy Alignment', indicator: 'ITU-AI-RF 2.0 — Indicator 2.1', severity: 'Moderate', recommendation: 'Create a cross-ministerial AI Task Force to map AI initiatives to specific SDG targets and national priorities.' },
    { id: "10", description: 'No AI regulatory sandbox framework for testing AI applications', dimension: 'AI Policy & Strategy', indicator: 'ITU-AI-RF 2.0 — Indicator 1.4', severity: 'Moderate', recommendation: 'Establish an AI Regulatory Sandbox managed by the ICT regulator to enable controlled AI testing.' },
    { id: "11", description: 'Limited multi-lingual AI support — local languages not represented in AI strategy', dimension: 'Contextualization & Regional Fit', indicator: 'ITU-AI-RF 2.0 — Indicator 7.2', severity: 'Moderate', recommendation: 'Include Swahili and other local languages as priority areas for NLP/AI research and development.' },
    { id: "12", description: 'No open government data policy or data sharing framework for AI research', dimension: 'Data & Model Ecosystem', indicator: 'ITU-AI-RF 2.0 — Indicator 3.3', severity: 'Critical', recommendation: 'Enact an Open Government Data Policy with mandatory data sharing for public-interest AI research.' },
  ],
  strengths: [
    'Tanzania has a formal National ICT Policy (2023) that explicitly references AI as a priority technology area.',
    'The country has enacted a Personal Data Protection Act (2022), establishing a foundational data governance framework.',
    'AI use cases are identified in both agriculture (precision farming) and health (diagnostic support) sectors.',
    'The strategy acknowledges alignment with the African Union Digital Transformation Strategy 2020-2030.',
    'Tanzania participates in regional EAC digital transformation initiatives, providing collaboration infrastructure.',
  ],
  priorityActions: [
    'Establish a National AI Coordination Council — Create a cross-ministerial body to oversee AI strategy implementation, allocate funding, and coordinate stakeholders. This addresses the most critical governance gap with moderate resource requirements.',
    'Launch an AI Ethics & Regulatory Framework — Develop and adopt a national AI ethics framework aligned with UNESCO recommendations, including mandatory impact assessments and a regulatory sandbox for AI innovation.',
    'Implement a Digital Literacy & Workforce Transition Program — Address the critical human impact gap by launching rural digital literacy initiatives and an AI workforce transition plan with reskilling components.',
  ],
}

export const recommendations: Recommendation[] = [
  {
    id: 'R-IM-1',
    title: 'Establish National AI Coordination Council',
    action: 'Form a cross-ministerial AI task force with representatives from ICT, Health, Agriculture, Education, Finance, and Labour. Publish a terms of reference within 60 days.',
    owner: 'Ministry of ICT / President\'s Office',
    resources: '2-3 FTE seconded staff, minimal budget',
    feasibility: 4,
    expectedOutcome: 'Coordinated AI governance structure operational within 6 months',
    risks: 'Inter-ministerial rivalry may slow formation',
    ituDimension: 'AI Policy & Strategy',
    sdgLink: 'SDG 9 (Industry, Innovation & Infrastructure), SDG 16 (Peace, Justice & Strong Institutions)',
  },
  {
    id: 'R-IM-2',
    title: 'Launch AI Ethics Framework Consultation',
    action: 'Conduct a 3-month multi-stakeholder consultation to draft a National AI Ethics Framework. Include academia, civil society, private sector, and development partners.',
    owner: 'Ministry of ICT',
    resources: 'Consultant budget ~$50,000, stakeholder workshop costs',
    feasibility: 4,
    expectedOutcome: 'Draft ethics framework ready for cabinet review in 4 months',
    risks: 'Consultation may surface divergent views delaying consensus',
    ituDimension: 'AI Policy & Strategy',
    sdgLink: 'SDG 16, SDG 10 (Reduced Inequalities)',
  },
  {
    id: 'R-ST-1',
    title: 'Develop Open Government Data Policy',
    action: 'Draft and enact an Open Government Data Policy mandating public sector data sharing for AI research. Include privacy safeguards and data standardization requirements.',
    owner: 'Ministry of ICT / National Bureau of Statistics',
    resources: 'Policy drafting team, legislative review, ~$100,000',
    feasibility: 3,
    expectedOutcome: 'Policy enacted within 12 months, AI research data repository operational in 18 months',
    risks: 'Data privacy concerns and inter-agency data sharing reluctance',
    ituDimension: 'Data & Model Ecosystem',
    sdgLink: 'SDG 9, SDG 17 (Partnerships for the Goals)',
  },
  {
    id: 'R-ST-2',
    title: 'Deploy AI Regulatory Sandbox',
    action: 'Establish a regulatory sandbox for AI applications under the ICT regulator (TCRA). Define application criteria, testing protocols, and graduation pathways.',
    owner: 'TCRA (Regulator)',
    resources: 'Regulatory staff training, IT platform, ~$200,000',
    feasibility: 3,
    expectedOutcome: 'Sandbox accepting applications within 12 months, 5-10 startups testing in year 2',
    risks: 'Regulatory capacity constraints may slow review cycles',
    ituDimension: 'AI Policy & Strategy',
    sdgLink: 'SDG 9, SDG 8 (Decent Work & Economic Growth)',
  },
  {
    id: 'R-MT-1',
    title: 'National Digital Literacy & AI Skilling Program',
    action: 'Design and deploy a nationwide digital literacy program targeting 60% rural coverage. Include AI awareness modules, basic digital skills, and advanced AI skilling tracks.',
    owner: 'Ministry of Education / Ministry of ICT',
    resources: '~$5M annually, partner with development agencies',
    feasibility: 3,
    expectedOutcome: '2M citizens trained in basic digital literacy, 10,000 AI professionals trained within 3 years',
    risks: 'Budget constraints and trainer availability in remote areas',
    ituDimension: 'Human Impact & Inclusion',
    sdgLink: 'SDG 4 (Quality Education), SDG 5 (Gender Equality), SDG 8',
  },
  {
    id: 'R-MT-2',
    title: 'National Compute & Cloud Infrastructure Strategy',
    action: 'Develop a national strategy for AI compute resources including public cloud procurement frameworks, GPU cluster investment, and research compute grants.',
    owner: 'Ministry of ICT / NICTBB',
    resources: '~$10-15M capital investment over 3 years',
    feasibility: 2,
    expectedOutcome: 'Government AI compute capacity established, research community access enabled',
    risks: 'High capital cost and ongoing operational expenditure',
    ituDimension: 'Digital Infrastructure',
    sdgLink: 'SDG 9, SDG 17',
  },
]

export const benchmarkData: BenchmarkData[] = [
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 55, benchmarkScore: 72 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 48, benchmarkScore: 65 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 32, benchmarkScore: 58 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 38, benchmarkScore: 55 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 28, benchmarkScore: 60 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 45, benchmarkScore: 70 },
  { primary: 'Tanzania', benchmark: 'Rwanda', primaryScore: 50, benchmarkScore: 68 },
]

export const benchmarkDimensions = [
  'AI Policy & Strategy',
  'Strategy Alignment',
  'Data & Model Ecosystem',
  'Cross-Domain Correlation',
  'Human Impact & Inclusion',
  'Digital Infrastructure',
  'Contextualization & Regional Fit',
]
